baseURL = ''
languageCode = 'en-us'
title = 'Rahul Setrakian'
theme = 'WarKnight'
enableInlineShortcodes = true


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20
  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio"
    weight = 30
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 40
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 50
